### ISSUE TITLE
Contrast curve with math error can not reshape

### ISSUE THREAD

**Issue by sdobler** [PynPoint/PynPoint#337]
I inserted today the latest version of the contrast curve calculation module. At some points my contrast curve does not converge and it gives a math domain error. During the reshaping of the results I then get a Value error as the shapes do not fit. I think the values of the places, where it could not converge, are missing. What can I do to solve the problem?

I wanted to calculate the contrast curve for a stacking of 75 frames and a PC subtraction of 45. The contrast curve does not converge at the innermost radius for three out of for angles.

A screenshot from my terminal with the error message is attached. 

![Screenshot from 2019-04-29 15-34-02](https://user-images.githubusercontent.com/50108446/56900473-39de0100-6a96-11e9-90c9-2253492674f7.png)

**Comment by tomasstolker** [comment]
Thanks for reporting this issue @sdobler.

Probably what is going wrong is that the value of `contrast` is negative when the `math.log10(contrast)` is calculated. I would guess that the `flux_out` term in the `attenuation` factor is negative. Could you verify this? I will then build in a check such that a NaN is written as output when the flux is negative such that reshaping of the array still works.

For now, the simple solution would be not calculating limits at a separation of 0.2 arcsec (in L'?) because the limits will be very poor anyway. In particular with such a large number of principal components (45), PCA will not be a robust method because you get strong self-subtraction effects. It will then also depend on how large your aperture size is. If the aperture is too large then you will include bright, negative self-subtraction regions which then may give an integrated negative flux.

This is my expectation though, please check if this is indeed the problem by rerunning the module and making a few print statements in `util.limits.contrast_limit`.

To see what PCA is doing at 0.2 arcsec with 45 components and a bright point source, you can run the `FakePlanetModule`. I would be interested to see the result so feel free to post it in this issue!

**Comment by sdobler** [comment]
Hi Tomas

It is as you guessed. The flux_out has a negative value for these angles. I think the problem is, that the contrast gets calculated at a place where most of the pixel have a negative value. 

I attached a pdf with fake planets. Once for a subtraction of 45 components and once 25 PC. The inserted signal is less visible for PC45 than for a PC subtraction of 25 (second page). But still the signal is visible. I used a magnitude difference of 7, that is what I get for contrast for PC 35 and Stacking 75. So I would suggest that maybe a subtraction of 45 components can be used. 
[Bug.pdf](https://github.com/PynPoint/PynPoint/files/3131668/Bug.pdf)

**Comment by tomasstolker** [comment]
Thanks for the test and sharing the results!

With 25 components, the result seems still useful. With 45 components, the self subtraction is indeed quite strong. Perhaps if you limit the aperture diameter to lambda/D (note that the value in PynPoint is the radius), it may still work.

I will create a pull request to fix the problem when the integrated flux is negative.

**Comment by tomasstolker** [comment]
This is fixed in pull request #339.
