### ISSUE TITLE
Multiprocessing bug

### ISSUE THREAD

**Issue by tomasstolker** [PynPoint/PynPoint#356]
There is bug in the multiprocessing tools of `util.multistack`. Somehow every 1000 images or so that are written, 8 of them are only partially stored for unclear reasons (independent of number of processes). This does not create an error or warning but it is visible in the images since part of them have values of zero. It is not clear to me if the problem is in the `multistack` utilities or at a higher level in `util.multiproc` (in which case it may also affects the multiprocessing in time). As a quick fix, I will disable the multiprocessing in `apply_function_to_images`.

**Comment by tomasstolker** [comment]
Multiprocessing of stacks of images with `apply_function_to_images` has been disabled with PR #357.

**Comment by tomasstolker** [comment]
I did an additional test in which in created a FITS cube of 1000 x 1000 x 10000 images (i.e. similar in size to the real data that I used before) with some random values. I ran the same procedure again (`RemoveLinesModule`) with and without the multiprocessing and tested the output of each image with `numpy.allclose`. Interestingly/surprisingly the problem did not occur in this case... That is, the output of the images was the same both with and without multiprocessing. I have no clue what this means... I also tested again on the real data, and the problem is still there...

With the real data, this is what an image looks like that was not properly stored (<= 1% of the data). Left is without multiprocessing and right is with multiprocessing:

![Screenshot 2019-05-21 at 08 57 53](https://user-images.githubusercontent.com/3204762/58101899-aef9ad80-7be0-11e9-8f90-e6acb30773f0.png)

Suggestions very much welcome...

**Comment by tomasstolker** [comment]
I have tested from the ``multiproc`` branch with a NACO dataset and have the same issue (as described above) both on Linux and macOS.

**Comment by benassa-de-glassa** [comment]
I can recreate the issue. But the differences occur for different frames than @tomasstolker described... For me those are: `[ 315  316  317  318  319  320  321  322  323  365  366  455  456 1485 1486 1487 1488 1489 1490 1491 1492 1493 1575 1576 1577 1578 1579 1580
 1581 1582 1583]`

![image](https://user-images.githubusercontent.com/33694956/59510794-e6443d00-8eb4-11e9-94a0-ed2d3e479d91.png)

**Comment by sdobler** [comment]
I tested the RemoveLinesModule on my NACO data and got an issue in the multiprocessing about every 7000 images. As for the others the lower section gets zero values.

/home/siri/Pictures/Issue_mp.png

**Comment by aboehle** [comment]
Hi @benassa-de-glassa and @sdobler, thanks very much for running these tests! Can you both also note if you ran tests that did not reproduce the error? This might help narrow down the issue. It'd also be great to know the dimensions of the input data set and the value of the memory parameter in your config file as @benassa-de-glassa included.

**Comment by sdobler** [comment]
@aboehle when I run the test code on my laptop I did not get the error, but due to limited memory I only used 2500 frames. So maybe these were just to few frames. The dataset I used has the dimension: (21600, 768, 768) and is from the ISPY project. The memory value was the default one.

**Comment by benassa-de-glassa** [comment]
@aboehle I did not reproduce the error on my NACO dataset on bluesky.
In the test I added in #366, I can reproduce the issue. It runs the `RemoveLinesModule` for 2000 frames. It uses the standard testing `config.ini` using `MEMORY=39`. The data has dimensons: (2000, 100, 100). 
To reproduce you can run: `pytest pynpoint/tests/test_processing/test_resizing.py`. The 6th test should fail. You may want to remove the fits output, or redirect it to a different folder.

**Comment by benassa-de-glassa** [comment]
@tomasstolker I've been debugging this the last view days. I can confirm that the bug occurs prior to the `apply_function` call in the `StackTaskProcessor.run_job()` function.

**Comment by aboehle** [comment]
I've run the test script on NACO L' data on tau ceti with 4137 total frames. I did *not* reproduce the error when running with `MEMORY = 1000`, both on a data set with frames of 1024 x 1024 pixels and a data set with frames of 149 x 149 pixels. When I tried other `MEMORY` values ranging from 5 to 1000 for the same `CPU = 4` on the 149 x 149 data set, I reproduced the similar error for some but not all `MEMORY` values. 

For every `MEMORY` value that I tried, the number of consecutive frames that were affected by the bug is always equal to the `stack_size`, which is a parameter passed into `StackProcessingCapsule` by `apply_function_to_images` that equals `int(MEMORY/CPU)`. Have others had this experience? 

Within the sets of consecutive frames, the affected pixels also seem to be in the same x/y location. The example below has the `CPU = 1` frame in the upper left, the same frame with `CPU = 4` in the upper right, and then the remaining consecutive frames processed with `CPU = 4` in the bottom row.

![Screen Shot 2019-06-18 at 11 02 15](https://user-images.githubusercontent.com/19195403/59668321-8f8e7a00-91b8-11e9-8199-f444fa997fac.png)

**Comment by benassa-de-glassa** [comment]
@aboehle 
> For every `MEMORY` value that I tried, the number of consecutive frames that were affected by the bug is always equal to the `stack_size`, which is a parameter passed into `StackProcessingCapsule` by `apply_function_to_images` that equals `int(MEMORY/CPU)`. Have others had this experience?

I've not had this experience. For me the largest number of consecutive affected frames is `int(MEMORY/CPU)`,  but there were also sets where fewer frames affected.

**Comment by aboehle** [comment]
@benassa-de-glassa For the cases where fewer frames were affected, were those the final frames in the input data set? I'm still running some tests and just had one case where this occurred, and I concluded that the final image stack is smaller just because there are no more frames left to process.

**Comment by benassa-de-glassa** [comment]
@aboehle No, they were everywhere in input data set.

**Comment by tomasstolker** [comment]
> it appears the issue lies in StackReader.run() . self.m_data_in_port contains the correct values, while tmp_data which is passed contains many zeros. I therefore suspect that the issue lies where the data is read from the database.

Thanks, that is good to know! So perhaps the `Lock` isn't working as expected... This should ensure that only one process reads/writes from/to the database.

**Comment by benassa-de-glassa** [comment]
The issue is very likely with the locking mechanism. A short term solution would be to read all data from the input_port into RAM, which obviously has the weak point of using a lot of RAM for large datasets. 

In the long term I see two solutions: 
 1. we figure out to get the locking mechanism to work
 1. HDF5 offers the possibilty of a _SingleWriterMultipleReader_ (SWMR) [[http://docs.h5py.org/en/stable/swmr.html](url)] mode (no locking required), which however requires the file to be opened individually by each Process with different `mode` and `swmr_mode` parameters. From what I can tell this would require some tinkering  with the core of pynpoint. I think this could be done by having different `open_connections` functions for the `InputPort`- and `OutputPort` classes, and opening and closing the connections whenever we want to read with multiple processes. I suspect the opening and closing of the file might slow down the modules, but I don't any experience with the opening speed of multiple hdf5 files.

**Comment by benassa-de-glassa** [comment]
> So perhaps the lock isn’t passed correctly between the readers and writers?

I've looked through the code, and to me it looks like the lock gets inherited correctly. `StackProcessingCapsule` inherits the lock from `MultiprocessingCapsule` and then passes it on to the `TaskReader` in the `init_creator()`function. Similarily the `TaskWriter.run()` also acquires the lock via context manager when accessing `self.m_data_out_port`. Maybe though, I missed a step in tracing the lock :D

**Comment by tomasstolker** [comment]
Perhaps the problem is related to opening of the database? Currently this happens once when a pipeline module starts running. Maybe a problem occurs if there are multiple processes using the same database object. So even though reading and writing only occurs by one process at a time, perhaps it is not possible to share the same database between processes.

A way to test this would be to close the output port at the start of the `apply_function_to_images` and then open and close the database each time the mutex is used. Note that the output port has to be opened again after all images have been processed such that the history and attributes can be written.

**Comment by benassa-de-glassa** [comment]
@aboehle 

> So perhaps the lock isn’t passed correctly between the readers and writers?

I tested this some more. I tried to run it without any locks, this caused the program to fail at exactly those `next_result.m_position` which have the corrupted images when running with the locks.

**Comment by tomasstolker** [comment]
> Perhaps the problem is related to opening of the database? Currently this happens once when a pipeline module starts running. Maybe a problem occurs if there are multiple processes using the same database object. So even though reading and writing only occurs by one process at a time, perhaps it is not possible to share the same database between processes.

After doing some tests, it seems that the problem is indeed related to the database. I will create a PR with a bug fix. The unit tests that @benassa-de-glassa added finish ok and the previous test on the NACO dataset shows no difference between the results with a single or multiple processes. It would good if a few of you test the new implementation as well, just to convince ourselves fully that the bug has been fixed... You can find the changes in the `multiproc` branch of `tomasstolker/PynPoint`.

**Comment by sdobler** [comment]
@tomasstolker I run the same database as before and did not get an output this time

**Comment by tomasstolker** [comment]
OK great, thanks for testing! I will close this issue and merge PR #372.
